CXX      = g++
CXXSTD   = -std=c++17
WARN     = -Wall -Wextra
OPT     ?= -O3
CXXFLAGS = $(CXXSTD) $(WARN) -I./inc $(OPT) -MMD -MP

SRC_DIR      = src
INC_DIR      = inc
EXAMPLES_DIR = examples
TESTS_DIR    = tests
BIN_DIR      = bin

SRCS = $(wildcard $(SRC_DIR)/*.cpp)
OBJS = $(SRCS:.cpp=.o)

EXAMPLE_SRCS = $(wildcard $(EXAMPLES_DIR)/*/main.cpp)
TARGETS      = $(patsubst $(EXAMPLES_DIR)/%/main.cpp,$(BIN_DIR)/%.exe,$(EXAMPLE_SRCS))

TEST_SRCS = $(wildcard $(TESTS_DIR)/*.cpp)
TEST_BINS = $(patsubst $(TESTS_DIR)/%.cpp,$(BIN_DIR)/%.exe,$(TEST_SRCS))

# Generated by -MMD: one .d per object/binary, listing the headers it includes.
# Without these, editing inc/*.hpp left stale objects linking against a changed
# header -- a silent ODR/ABI mismatch.
DEPS = $(OBJS:.o=.d) $(TARGETS:.exe=.d) $(TEST_BINS:.exe=.d)

.PHONY: all clean test asan release
.SECONDARY: $(OBJS)

all: $(TARGETS)

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

$(BIN_DIR)/%.exe: $(EXAMPLES_DIR)/%/main.cpp $(OBJS) | $(BIN_DIR)
	$(CXX) $(CXXFLAGS) $< $(OBJS) -o $@

$(BIN_DIR)/%.exe: $(TESTS_DIR)/%.cpp $(OBJS) | $(BIN_DIR)
	$(CXX) $(CXXFLAGS) $< $(OBJS) -o $@

$(SRC_DIR)/%.o: $(SRC_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Build and run the gradient-check / regression suite.
test: $(TEST_BINS)
	@for t in $(TEST_BINS); do echo "== $$t"; ./$$t || exit 1; done

# Same suite under AddressSanitizer + UndefinedBehaviorSanitizer.
asan:
	$(MAKE) clean
	$(MAKE) test OPT="-O1 -g -fsanitize=address,undefined -fno-omit-frame-pointer"

# Index bounds checks compile out under NDEBUG; tape integrity and domain
# checks stay on.
release:
	$(MAKE) clean
	$(MAKE) all OPT="-O3 -DNDEBUG"

clean:
	rm -f $(OBJS) $(DEPS)
	rm -rf $(BIN_DIR)

-include $(DEPS)
